### ISSUE TITLE
Damping for Nosé Hoover

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_lammps#4]
I see that the damping parameters of Nosé Hoover for both the thermostat and the barostat are set to be 1.0, but according to the [LAMMPS website](https://lammps.sandia.gov/doc/fix_nh.html), the recommended values are 100 for the temperature and 1,000 for the pressure. Isn't it better to take these values as default?

**Comment by jan-janssen** [comment]
Sounds like a good idea to me - can you update the defaults?

**Comment by jan-janssen** [comment]
Done in https://github.com/pyiron/pyiron_lammps/pull/5
